async (page) => {
  const base = page.url().split('/v2/')[0] + '/v2/';
  const results = [];
  const assert = (condition, message) => { if (!condition) throw new Error(message); results.push(message); };
  const errors = [];
  const onError = error => errors.push(error.message);
  page.on('pageerror', onError);
  await page.emulateMedia({ reducedMotion: 'reduce' });
  await page.setViewportSize({width: 1440, height: 1000});
  await page.goto(base);
  const total = await page.locator('.catalog-card[data-category]').count();
  assert(total >= 20, 'Full project catalogue has at least 20 entries');
  assert(await page.locator('.case-feature').count() === 6, 'Six featured case studies');
  assert(await page.locator('.catalog-controls').isVisible(), 'Progressive enhancement enables filters');
  await page.locator('[data-filter="ai"]').click();
  assert(await page.locator('.catalog-card:visible').count() > 0, 'AI category returns projects');
  assert(await page.locator('.catalog-card:visible').evaluateAll(cards => cards.every(c => c.dataset.category === 'ai')), 'Category filter excludes other categories');
  await page.locator('#project-search').fill('zzzz-no-such-project');
  assert(await page.locator('.catalog-card:visible').count() === 0 && await page.locator('#empty-state').isVisible(), 'Combined filter and search show accessible empty state');
  await page.locator('#project-search').fill('');
  await page.locator('[data-filter="all"]').click();
  assert(await page.locator('.catalog-card:visible').count() === total, 'Reset category restores complete catalogue');
  const href = await page.locator('.case-feature').first().getAttribute('href');
  await page.locator('.case-feature').first().click();
  assert(await page.evaluate(() => location.pathname) === href, 'Featured case opens a real detail URL');
  assert(await page.locator('.case-story').count() === 3, 'Case includes problem, solution and result');
  await page.locator('.case-breadcrumb').click();
  assert(await page.evaluate(() => location.pathname) === '/v2/', 'Case returns to portfolio catalogue');
  await page.locator('#brief').scrollIntoViewIfNeeded();
  await page.locator('#brief-next').click();
  assert((await page.locator('#step-label').innerText()).includes('01'), 'Brief cannot continue without a selection');
  await page.getByRole('radio', { name: 'AI и автоматизация', exact: false }).check();
  await page.locator('#brief-next').click();
  assert((await page.locator('#step-label').innerText()).includes('02'), 'Brief proceeds to current situation');
  await page.locator('#brief-back').click();
  assert(await page.getByRole('radio', { name: 'AI и автоматизация', exact: false }).isChecked(), 'Back navigation preserves selection');
  await page.locator('#brief-next').click();
  await page.getByRole('radio', { name: '1С или CRM', exact: false }).check();
  await page.locator('#brief-next').click();
  await page.getByRole('radio', { name: 'Запустить работающий инструмент', exact: false }).check();
  const note = 'Проверка: данные из трёх филиалов. <script>test</script>';
  await page.locator('#brief-detail').fill(note);
  await page.locator('#brief-back').click();
  await page.locator('#brief-next').click();
  assert(await page.locator('#brief-detail').inputValue() === note, 'Free text survives back and forward');
  await page.locator('#brief-next').click();
  assert(await page.locator('#brief-result').isVisible(), 'Brief produces a reviewable summary');
  const summary = await page.locator('#brief-summary').innerText();
  assert(summary.includes(note) && summary.includes('1С или CRM'), 'Summary preserves Unicode and renders user text literally');
  const contact = await page.locator('#brief-send').evaluate(a => { const url = new URL(a.href); return {origin:url.origin,pathname:url.pathname,text:url.searchParams.get('text')}; });
  assert(contact.origin === 'https://wa.me' && contact.pathname === '/77019149520' && contact.text === summary, 'WhatsApp handoff uses correct contact and encoded summary; not sent');
  const downloadPromise = page.waitForEvent('download');
  await page.locator('#brief-download').click();
  const download = await downloadPromise;
  assert(download.suggestedFilename() === 'refactor-task.txt', 'Brief downloads a named text file');
  await page.locator('#brief-reset').click();
  assert(await page.locator('#brief-form').isVisible() && !(await page.locator('#brief-result').isVisible()), 'Reset returns to a fresh brief');
  assert(await page.locator('input[name=answer]:checked').count() === 0, 'Reset clears prior answers');
  await page.setViewportSize({width:390, height:844});
  await page.evaluate(() => scrollTo(0, 0));
  const menu = page.locator('.menu-toggle');
  await menu.click();
  assert(await menu.getAttribute('aria-expanded') === 'true', 'Mobile navigation opens');
  assert(await page.locator('#main-nav a').first().evaluate(el => el === document.activeElement), 'Mobile navigation moves keyboard focus into menu');
  await page.keyboard.press('Escape');
  assert(await menu.getAttribute('aria-expanded') === 'false', 'Escape closes mobile navigation');
  assert(await menu.evaluate(el => el === document.activeElement), 'Escape restores menu trigger focus');
  await menu.click();
  await page.locator('#main-nav a').first().click();
  assert(await menu.getAttribute('aria-expanded') === 'false', 'Choosing section closes mobile navigation');
  for (const width of [360, 390, 640, 768, 1024, 1440]) {
    await page.setViewportSize({width, height:900});
    assert(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth), `No horizontal overflow at ${width}px`);
  }
  assert(await page.locator('.sculpture').evaluate(el => getComputedStyle(el).animationName === 'none'), 'Reduced motion stops hero animation');
  const links = await page.locator('a[href]').evaluateAll(elements => [...new Set(elements.map(e => e.href).filter(href => new URL(href).origin === location.origin))]);
  const responses = await Promise.all(links.map(async href => ({href, status: (await page.request.get(href)).status()})));
  assert(responses.every(r => r.status === 200), 'All local homepage links return HTTP 200');
  const badImages = await page.locator('img').evaluateAll(imgs => imgs.filter(img => img.complete && img.naturalWidth === 0).map(img => img.src));
  assert(badImages.length === 0, 'No broken loaded images');
  assert(errors.length === 0, 'No browser runtime errors');
  const noJsContext = await page.context().browser().newContext({javaScriptEnabled:false, viewport:{width:390,height:844}});
  const noJs = await noJsContext.newPage();
  await noJs.goto(base);
  assert(await noJs.locator('.catalog-card').count() === total, 'All project content remains available without JavaScript');
  assert(await noJs.locator('noscript a').first().isVisible(), 'Contact fallback works without JavaScript');
  assert(!(await noJs.locator('.catalog-controls').isVisible()), 'Nonworking filters stay hidden without JavaScript');
  await noJsContext.close();
  page.off('pageerror', onError);
  await page.setViewportSize({width:1440,height:1000});
  await page.goto(base);
  return {passed:results.length,projectCount:total,checks:results};
}
